export default {
  GET_USER_DATA: 'GET_USER_DATA',
  GET_USER_DATA_SUCCESS: 'GET_USER_DATA_SUCCESS',
  GET_USER_DATA_ERROR: 'GET_USER_DATA_ERROR',

  USER_FORM_CHNGED: 'USER_FORM_CHNGED',
  SET_VALIDATION_ERROR: 'SET_VALIDATION_ERROR',
  CLEAR_ERRORS: 'CLEAR_ERRORS',

  UPDATE_USER_DATA: 'UPDATE_USER_DATA',
  UPDATE_USER_DATA_SUCCESS: 'UPDATE_USER_DATA_SUCCESS',
  UPDATE_USER_DATA_ERROR: 'UPDATE_USER_DATA_ERROR',
}
